### PR TITLE
Feature/739 Timeout Sequence Diagrams Bulk Adaptation

### PR DESCRIPTION
**Pull request by ggrg**
[Story #739](https://github.com/mojaloop/project/issues/739)

### CODE REVIEW

**Comment by elnyry-sam-k** [comment]
hi Georgi, a few observations:

1. Steps 9,10,11,12 (Consume and send callback) in the timeout 2.3.0 sequence diagram seem redundant as they're already present in the referenced notification Sequence diagram
2. We need to discuss a bit more about bulk timeouts on received and reserved, since it doesn't have a reserved state technically

**Comment by ggrg** [comment]
Thanks for commenting, @elnyry. 
1. This redundancy is intended and common for all diagrams, where we use **ref** in order to show the input and output of the process. (Same for steps 1, 2, 3 - part of ref to 2.3.1 and 5, 6 - part of ref to 1.3.3)
2. Bulk doesn't but, here we observe and work with the states of the individual transfers, right? Or am I missing something?

**Comment by elnyry-sam-k** [comment]
The one aspect I'm thinking for #2 is - if it is the individual transfers then shouldn't they just be reserved or received? this may need more discussion - lets discuss this later today

**Comment by elnyry-sam-k** [comment]
One more thing, just wanted to leave here for discussion. Is Step#8 needed in 2.3.0 as we have 9-12?

**Pull request closed without merging**
